AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Layer 
Resources:

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: my-lambda-layer
      Description: My Lambda Layer
      Content:
          S3Bucket: "<bucket-name>"
          S3Key: "<prefix>"
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: lambda_layer_role
          PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*

  LayerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event,context):
              print(event)
              print(context)
              print("Hello World From Lambda")
              greeting1()
              greeting2()
              return "Finished"     
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Layers:
        - !Ref LambdaLayer
      Runtime: python3.10
      Timeout: 10 